// Workouts
const GET_WORKOUTS_STARTED = 'GET_WORKOUTS_STARTED';
const GET_WORKOUTS_SUCCESS = 'GET_WORKOUTS_SUCCESS';
const GET_WORKOUTS_ERROR = 'GET_WORKOUTS_ERROR';

// Drawer Menu
const TOGGLE_DRAWER_MENU = 'TOGGLE_DRAWER_MENU';

// Music player
const TOGGLE_MUSIC_PLAYER = 'TOGGLE_MUSIC_PLAYER';
const START_MUSIC_PLAYER_EVENT = 'START_MUSIC_PLAYER_EVENT';
const STOP_MUSIC_PLAYER_EVENT = 'STOP_MUSIC_PLAYER_EVENT';
const PAUSE_MUSIC_PLAYER_EVENT = 'PAUSE_MUSIC_PLAYER_EVENT';
const SET_MUSIC_PLAYER_PLAYLIST = 'SET_MUSIC_PLAYER_PLAYLIST';

// Service worker
const SW_INIT = 'SW_INIT';
const SW_UPDATE = 'SW_UPDATE';

export {
  GET_WORKOUTS_STARTED,
  GET_WORKOUTS_SUCCESS,
  GET_WORKOUTS_ERROR,
  TOGGLE_DRAWER_MENU,
  TOGGLE_MUSIC_PLAYER,
  START_MUSIC_PLAYER_EVENT,
  STOP_MUSIC_PLAYER_EVENT,
  PAUSE_MUSIC_PLAYER_EVENT,
  SET_MUSIC_PLAYER_PLAYLIST,
  SW_INIT,
  SW_UPDATE,
};
