// Workouts
const GET_WORKOUTS_STARTED = 'GET_WORKOUTS_STARTED';
const GET_WORKOUTS_SUCCESS = 'GET_WORKOUTS_SUCCESS';
const GET_WORKOUTS_ERROR = 'GET_WORKOUTS_ERROR';

// Drawer Menu
const TOGGLE_DRAWER_MENU = 'TOGGLE_DRAWER_MENU';

export {
  GET_WORKOUTS_STARTED,
  GET_WORKOUTS_SUCCESS,
  GET_WORKOUTS_ERROR,
  TOGGLE_DRAWER_MENU,
};
